# Generated by Django 5.1 on 2024-09-06 14:24

import autoslug.fields
import django.core.validators
import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Property Title')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('ref_code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Property Reference')),
                ('description', models.TextField(default='Please Enter Description', verbose_name='Description')),
                ('country', django_countries.fields.CountryField(default='PK', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Lahore', max_length=100, verbose_name='city')),
                ('postal_code', models.CharField(default=58810, max_length=100, verbose_name='Postal Code')),
                ('street_address', models.CharField(default='Airport Road', max_length=255, verbose_name='Street Address')),
                ('property_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Property Number')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Property Price')),
                ('tax', models.DecimalField(decimal_places=2, default=0.15, help_text='15% OF Property Price', max_digits=6, verbose_name='Property Tax')),
                ('plot_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Property Area(m**2)')),
                ('total_floors', models.IntegerField(default=1, verbose_name='Total Floors')),
                ('bedrooms', models.IntegerField(default=1, verbose_name='Total Bedrooms')),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1.0, max_digits=6, verbose_name='Total Bathrooms')),
                ('advert_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('For Auction', 'For Auction')], default='For Sale', max_length=50, verbose_name='Advertise Type')),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Appartment', 'Appartment'), ('Office', 'Office'), ('Warehouse', 'Warehouse'), ('Commercial', 'Commercial'), ('Other', 'Other')], default='House', verbose_name='Property Type')),
                ('cover_photo', models.ImageField(blank=True, default='/house_photo.png', null=True, upload_to='', verbose_name='Mian Photo')),
                ('photo1', models.ImageField(blank=True, default='/house_photo.png', null=True, upload_to='', verbose_name='Mian Photo')),
                ('photo2', models.ImageField(blank=True, default='/house_photo.png', null=True, upload_to='', verbose_name='Mian Photo')),
                ('photo3', models.ImageField(blank=True, default='/house_photo.png', null=True, upload_to='', verbose_name='Mian Photo')),
                ('photo4', models.ImageField(blank=True, default='/house_photo.png', null=True, upload_to='', verbose_name='Mian Photo')),
                ('published_status', models.BooleanField(default=False, verbose_name='Published Status')),
                ('views', models.IntegerField(default=0, verbose_name='Total Views')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Agent,Seller or Buyer')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyViews',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=50, verbose_name='IP Address')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_views', to='properties.property')),
            ],
            options={
                'verbose_name': 'Total Property Views',
                'verbose_name_plural': 'Total Property Views',
            },
        ),
    ]
