# Generated by Django 5.1 on 2024-09-24 07:50

import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyviews',
            options={'verbose_name': 'Total Views on Property', 'verbose_name_plural': 'Total Property Views'},
        ),
        migrations.AlterField(
            model_name='property',
            name='advert_type',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Auction', 'Auction')], default='For Sale', max_length=50, verbose_name='Advert Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=1, verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='Nairobi', max_length=180, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=django_countries.fields.CountryField(default='KE', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='property',
            name='cover_photo',
            field=models.ImageField(blank=True, default='/house_sample.jpg', null=True, upload_to='', verbose_name='Main Photo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='Default description...update me please....', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo1',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo2',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo3',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo4',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Plot Area(m^2)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.CharField(default='140', max_length=100, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_number',
            field=models.IntegerField(default=112, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Property Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('Warehouse', 'Warehouse'), ('Commercial', 'Commercial'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ref_code',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Property Reference Code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_address',
            field=models.CharField(default='KG8 Avenue', max_length=150, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.15, help_text='15% property tax charged', max_digits=6, verbose_name='Property Tax'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(default=0, verbose_name='Number of floors'),
        ),
        migrations.AlterField(
            model_name='propertyviews',
            name='ip',
            field=models.CharField(max_length=250, verbose_name='IP Address'),
        ),
    ]
